####################################
# HostGuard Configuration
####################################

# Providers
ENABLE_SPAMHAUS=yes
ENABLE_EDROP=yes

# Firewall
BLOCK_SSH=yes
BLOCK_SMTP=yes
BLOCK_RDP=no

# Auto Update
AUTO_UPDATE=yes

# Backend
FIREWALL=iptables

# Logging
ENABLE_LOG=yes
